# Generated by Django 4.0.3 on 2022-03-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_form_number_patient_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_tracing', to='users.userinfo')),
            ],
        ),
    ]
