# Generated by Django 4.0.3 on 2022-03-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contacttracing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTracing',
        ),
    ]
