# Generated by Django 4.0.2 on 2022-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_contacttracing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlist',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
