# Generated by Django 4.0.2 on 2022-03-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointment'),
        ('users', '0004_delete_contacttracing'),
    ]

    operations = [
    ]
