# Generated by Django 4.0.1 on 2022-03-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0002_appointment_0004_delete_contacttracing'),
        ('users', '0005_patientlist_is_new'),
    ]

    operations = [
    ]
