# Generated by Django 4.0.2 on 2022-04-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20220329_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_new',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_contact_tracing',
            field=models.BooleanField(default=False),
        ),
    ]
