# Generated by Django 4.0.2 on 2022-04-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinfo_hasmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='hasCTForm',
            field=models.BooleanField(default=False),
        ),
    ]
