# Generated by Django 4.0.2 on 2022-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_patient_is_new_patient_is_contact_tracing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_update_daily_form',
            field=models.BooleanField(default=False),
        ),
    ]
