# Generated by Django 4.0.2 on 2022-04-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_patient_is_update_daily_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_quarantine',
            field=models.BooleanField(default=False),
        ),
    ]
