# Generated by Django 4.0.1 on 2022-04-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userinfo_hasctform'),
        ('users', '0009_patient_is_quarantine'),
    ]

    operations = [
    ]
