# Generated by Django 4.0.1 on 2022-04-01 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20220329_2209'),
        ('patientStuff', '0003_contacttracing_contact_info_covid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttracing',
            name='user_info',
        ),
        migrations.AddField(
            model_name='contacttracing',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_tracing', to='users.patient'),
        ),
    ]
